language: perl
install:
  - cpanm --quiet --installdeps --notest --with-configure .
matrix:
  include:
    - perl: "5.8"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.30"
